context:
  version: "4.43.5"

package:
  name: stencil-core
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/@stencil/core/-/core-${{ version }}.tgz
  sha256: be1dd44493e6ebe6307d7cbf643b658d0239b4721b69258899222844e2b5edad

build:
  number: 0
  noarch: generic

requirements:
  build:
    - nodejs
  run:
    - nodejs

tests:
  - script:
      - stencil --help

about:
  license: MIT
  license_file: LICENSE.md
  summary: A Compiler for Web Components and Progressive Web Apps
  homepage: https://stenciljs.com/
  repository: https://github.com/ionic-team/stencil

extra:
  recipe-maintainers:
    - danielnachun
