context:
  version: "4.27.1"

package:
  name: stencil-core
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/@stencil/core/-/core-${{ version }}.tgz
  sha256: 7e4c940c7f417b8d7d0390c5a101179894e8156c7e8d556b2abe624e3c473b69

build:
  number: 0
  noarch: generic

requirements:
  build:
    - nodejs
  run:
    - nodejs

tests:
  - script:
      - stencil --help

about:
  license: MIT
  license_file: LICENSE.md
  summary: A Compiler for Web Components and Progressive Web Apps
  homepage: https://stenciljs.com/
  repository: https://github.com/ionic-team/stencil

extra:
  recipe-maintainers:
    - danielnachun
