context:
  version: "4.40.1"

package:
  name: stencil-core
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/@stencil/core/-/core-${{ version }}.tgz
  sha256: c133fbdc9eb08a51f4e8b7e24a0599b84f0e514dbaadacba313f9d607f14f242

build:
  number: 0
  noarch: generic

requirements:
  build:
    - nodejs
  run:
    - nodejs

tests:
  - script:
      - stencil --help

about:
  license: MIT
  license_file: LICENSE.md
  summary: A Compiler for Web Components and Progressive Web Apps
  homepage: https://stenciljs.com/
  repository: https://github.com/ionic-team/stencil

extra:
  recipe-maintainers:
    - danielnachun
