context:
  version: "4.26.0"

package:
  name: stencil-core
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/@stencil/core/-/core-${{ version }}.tgz
  sha256: 9cdefda19e4e7f7b6edc12a0a0b76204cd9aa926684cea9e7bf822f362ed1ddf

build:
  number: 0
  noarch: generic

requirements:
  build:
    - nodejs
  run:
    - nodejs

tests:
  - script:
      - stencil --help

about:
  license: MIT
  license_file: LICENSE.md
  summary: A Compiler for Web Components and Progressive Web Apps
  homepage: https://stenciljs.com/
  repository: https://github.com/ionic-team/stencil

extra:
  recipe-maintainers:
    - danielnachun
