context:
  version: "4.25.3"

package:
  name: stencil-core
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/@stencil/core/-/core-${{ version }}.tgz
  sha256: 8169123e4af72b35708bff078d443e0164aac22726f87a83ae71c613513ce037

build:
  number: 0
  noarch: generic

requirements:
  build:
    - nodejs
  run:
    - nodejs

tests:
  - script:
      - stencil --help

about:
  license: MIT
  license_file: LICENSE.md
  summary: A Compiler for Web Components and Progressive Web Apps
  homepage: https://stenciljs.com/
  repository: https://github.com/ionic-team/stencil

extra:
  recipe-maintainers:
    - danielnachun
